plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'config/environments/**/*'
    - 'config/initializers/**/*'

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false

# frozen_string_literal commentを必須としない
Style/FrozenStringLiteralComment:
  Enabled: false

# メソッドの長さ制限を緩和
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

# ブロックの長さ制限を緩和
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

# クラスの長さ制限を緩和
Metrics/ClassLength:
  Max: 150

# 行の長さ制限
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# ドキュメントコメントを必須としない
Style/Documentation:
  Enabled: false

# 文字列リテラルのスタイル
Style/StringLiterals:
  EnforcedStyle: single_quotes

# シンボル配列のスタイル
Style/SymbolArray:
  EnforcedStyle: brackets

# 単語配列のスタイル
Style/WordArray:
  EnforcedStyle: brackets

# RSpec関連のルールを実用的に緩和
RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

# let! を setup データとして使用することを許可
RSpec/LetSetup:
  Enabled: false

# memoized helpers の上限を引き上げ
RSpec/MultipleMemoizedHelpers:
  Max: 10

# インデックス付きlet変数名を許可
RSpec/IndexedLet:
  Enabled: false

# subject に名前を付けなくても OK
RSpec/NamedSubject:
  Enabled: false

# テストでのバリデーションスキップを許可
Rails/SkipsModelValidations:
  Enabled: false